deployment:
  image:
    repository: 002665144501.dkr.ecr.eu-central-1.amazonaws.com/bf-api-foundation-authentication
  env:
    ENVIRONMENT: dev
hostName: authentication.bridgefund-foundation-development.net
#deployment
