const { Config } = require('../../../../../config');
const FrontEndUrl = Config.FRONTEND_URL;

const LM_Routes = {
  user: [{
    name: 'Loan Management',
    icon: 'HowToVote',
    rtlName: '',
    layout: '/user',
    hide: false,
    children: [{
      name: 'Dashboard',
      icon: 'Dashboard',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/user',
      path: '/lm-dashboard',
      component: 'DashboardPageLM',
      cluster: 'LoanManagement',
      permission: 'LM-dashboard',
      hide: false
    }, {
      name: 'Loans',
      icon: 'AccountBalance',
      rtlName: '',
      layout: '/user',
      hide: false,
      children: [{
        name: 'Customer List',
        icon: 'Ballot',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeList',
        component: 'SmeListLM',
        cluster: 'LoanManagement',
        permission: 'LM-customer-list',
        hide: false,
      }, {
        name: 'Single Loan',
        icon: 'ListAlt',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/singleLoanOverview/:contractId',
        component: 'SingleLoanOverview',
        cluster: 'LoanManagement',
        permission: 'LM-single-loan-overview',
        hide: true
      }, {
        name: 'Flex Loan Overview',
        icon: 'Ballot',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/FlexLoanOverview',
        component: 'FlexLoanOverview',
        cluster: 'LoanManagement',
        permission: 'LM-flex-loan-overview',
        hide: false,
        children: [{
          name: 'Flex Loan Overview',
          icon: 'ListAlt',
          rtlName: '',
          origin: FrontEndUrl.LM_PORTAL_URL,
          layout: '/user',
          path: '/flexLoanOverview/:contractId',
          component: 'FlexLoanOverview',
          cluster: 'LoanManagement',
          permission: 'LM-flex-loan-overview',
          hide: true
        }]
      }, {
        name: 'Transactions',
        icon: 'AccountBalanceWallet',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeLoanTransactions',
        component: 'SmeLoanTransactionsList',
        cluster: 'LoanManagement',
        permission: 'LM-transactions-editor',
        hide: false,
      }, {
        name: 'Appointments',
        icon: 'LoanRecoveryAppointmentIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeLoanRecoveryAppointment',
        component: 'SmeLoanRecoveryAppointment',
        cluster: 'LoanManagement',
        permission: 'LM-loan-recovery-appointments-overview',
        hide: false,
      }, {
        name: 'User Profile ',
        icon: 'Person',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeProfile/:customerId',
        component: 'Overview',
        cluster: 'LoanManagement',
        permission: 'LM-user-profile',
        hide: true
      }, {
        name: 'Chamber Of Commerce',
        icon: 'Person',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/chamberOfCommerce/:customerId',
        component: 'ChamberOfCommerce',
        cluster: 'LoanManagement',
        permission: 'LM-chamber-of-commerce',
        hide: true
      }]
    }, {
      name: 'Asset Management',
      icon: 'PriorityHigh',
      rtlName: '',
      layout: '/user',
      hide: false,
      children: [{
        name: 'Customer List',
        icon: 'Ballot',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeList',
        component: 'SmeList',
        cluster: 'LoanManagement',
        permission: 'LM-customer-list',
        hide: false,
      }, {
        name: 'Late Payments',
        icon: 'LoanLatePaymentOverviewIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/loanLatePaymentOverview',
        component: 'LoanLatePaymentOverview',
        cluster: 'LoanManagement',
        permission: 'LM-loan-late-payments-overview',
        hide: false,
      }, {
        name: 'Appointments',
        icon: 'LoanRecoveryAppointmentIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeLoanRecoveryAppointment',
        component: 'SmeLoanRecoveryAppointment',
        cluster: 'LoanManagement',
        permission: 'LM-loan-recovery-appointments-overview',
        hide: false,
      }, {
        name: 'Multiple Loans',
        icon: 'MultipleLoanOverviewIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/multipleLoanOverview',
        component: 'MultipleLoanOverview',
        cluster: 'LoanManagement',
        permission: 'LM-multiple-loan-overview',
        hide: false,
      }]
    }, {
      name: 'Finance',
      icon: 'Euro',
      rtlName: '',
      layout: '/user',
      hide: false,
      children: [{
        name: 'Customer List',
        icon: 'Ballot',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/smeList',
        component: 'SmeList',
        cluster: 'LoanManagement',
        permission: 'LM-customer-list',
        hide: false,
      }, {
        name: 'Bank Transaction',
        icon: 'BankTransactionIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/bankTransactionOverview',
        component: 'BankTransactionOverview',
        cluster: 'LoanManagement',
        permission: 'LM-bank-transaction',
        hide: false,
      }, {
        name: 'Approve DD Batch',
        icon: 'ListAlt',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/directDebitBatchDetails',
        component: 'DirectDebitBatchDetails',
        cluster: 'LoanManagement',
        permission: 'LM-approve-dd-batch',
        hide: false,
      }, {
        name: 'Spreadrisk',
        icon: 'SpreadRiskIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/spreadRiskOverview',
        component: 'SpreadRiskOverview',
        cluster: 'LoanManagement',
        permission: 'LM-spread-risk-overview',
        hide: false,
      }, {
        name: 'Provision',
        icon: 'ProvisionOverviewIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/provisionOverview',
        component: 'ProvisionOverview',
        cluster: 'LoanManagement',
        permission: 'LM-provision-overview',
        hide: false,
      }, {
        name: 'Book Income',
        icon: 'TrendingUp',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/BookSmeLoanPlannedIncome',
        component: 'BookPlannedIncome',
        cluster: 'LoanManagement',
        permission: 'LM-book-planned-income',
        hide: false,
      }, {
        name: 'Liquidity',
        icon: 'Assessment',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/LiquidityRequirementsOverview',
        component: 'LiquidityRequirementsOverview',
        cluster: 'LoanManagement',
        permission: 'LM-liquidity-overview',
        hide: false,
      }, {
        name: 'Multiple Loans',
        icon: 'MultipleLoanOverviewIcon',
        rtlName: '',
        origin: FrontEndUrl.LM_PORTAL_URL,
        layout: '/user',
        path: '/multipleLoanOverview',
        component: 'MultipleLoanOverview',
        cluster: 'LoanManagement',
        permission: 'LM-multiple-loan-overview',
        hide: false,
      }]
    }]
  }],
  admin: [{
    name: 'Loan Management',
    icon: 'HowToVote',
    rtlName: '',
    layout: '/admin',
    hide: false,
    children: [{
      name: 'Admin Dashboard',
      icon: 'Dashboard',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/dashboard',
      component: 'AdminDashboard',
      cluster: 'LoanManagement',
      permission: 'LM-admin-dashboard',
      hide: false
    },
    {
      name: 'Temporary Loan Stop',
      icon: 'Pause',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/temporaryLoanStop',
      component: 'LoanTemporaryStop',
      cluster: 'LoanManagement',
      permission: 'LM-temporary-loan-stop',
      hide: false
    },
    {
      name: 'Settings',
      icon: 'Settings',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/settings',
      component: 'SettingsView',
      cluster: 'LoanManagement',
      permission: 'LM-settings',
      hide: true
    },
    {
      name: 'Provision Parameters',
      icon: 'ScatterPlot',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/provisionParameters',
      component: 'ProvisionParameters',
      cluster: 'LoanManagement',
      permission: 'LM-provision-parameter',
      hide: false
    },
    {
      name: 'Notifications',
      icon: 'Help',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/notifications',
      component: 'Notifications',
      cluster: 'LoanManagement',
      permission: 'LM-notifications',
      hide: false
    },
    {
      name: 'Direct Debit Batch Details',
      icon: 'ListAlt',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/directDebitBatchDetails',
      component: 'DirectDebitBatchDetails',
      cluster: 'LoanManagement',
      permission: 'LM-dd-batch-details',
      hide: false
    },
    {
      name: 'Transaction list',
      icon: 'AccountBalanceWallet',
      rtlName: '',
      origin: FrontEndUrl.LM_PORTAL_URL,
      layout: '/admin',
      path: '/smeLoanTransactions',
      component: 'SmeLoanTransactionsList',
      cluster: 'LoanManagement',
      permission: 'LM-transactions-editor',
      hide: false
    },
    ]
  }]
};

module.exports = [].concat(LM_Routes.user, LM_Routes.admin);
